### PR TITLE
Include the list of unloaded modules in the output (#22)

### PR DESCRIPTION
**Pull request by gabrielesvelto**

### CODE REVIEW

**Comment by willkg** [comment]
Do you have a crash report or a minidump to test this with?

**Comment by gabrielesvelto** [comment]
This one has the right code and subcode to test: https://crash-stats.mozilla.org/report/index/39fe2c2e-2fc6-4bd1-a03f-e3d2c0210408

**Comment by gabrielesvelto** [comment]
> This one has the right code and subcode to test: https://crash-stats.mozilla.org/report/index/39fe2c2e-2fc6-4bd1-a03f-e3d2c0210408

I actually meant that this crash has an unloaded module. I was working on a separate issue and my brain mixed up both things.

**Comment by gabrielesvelto** [comment]
Note that for now what's going to happen is that the raw JSON output will contain a new field (`unloaded_modules`) so it shouldn't change anything for the front-end save for the raw view where it will be shown. I'll file a separate bug once this lands to decide what we want to do with that list in the crash view (if we want to add them to the Modules tab, if we want them in a separate tab, etc...).

**Review by willkg — APPROVED** [review]
I went through a bunch of crash reports and most of them have unloaded modules. Everything looks good as far as I can tell.

**Pull request merged**
