### PR TITLE
bug 1661605: add circle ci configuration

### PR DESCRIPTION
**Pull request by willkg**
This adds configuration for building an image and pushing it to docker hub. It'll build :latest for all merges to main and it'll build :TAG for tags.

### CODE REVIEW

**Comment by willkg** [comment]
@sciurus : Does this look right? After landing this, what's the next step for setting it up in Circle CI and then for pushing images to docker hub?

**Comment by sciurus** [comment]
I'm not great with circle pipelines, but at a glance this seems ok.

I'll need to setup the dockerhub repo and add the secrets to push to it to https://app.circleci.com/pipelines/github/mozilla-services/minidump-stackwalk. I can do that a little later today. I created https://bugzilla.mozilla.org/show_bug.cgi?id=1662132 for it.

**Comment by willkg** [comment]
If it helps, I copied this one from socorro and then tweaked it.

**Review by sciurus — APPROVED** [review]

**Comment by sciurus** [comment]
@willkg I used what you suggested on slack, which has hyphens instead of underscores.

https://hub.docker.com/r/mozilla/socorro-minidump-stackwalker

**Comment by sciurus** [comment]
Circle CI env vars are in place now.

**Comment by willkg** [comment]
I'll change it to hyphens. I think Socorro and other things use underscores. I don't know if we have conventions.

**Comment by sciurus** [comment]
> I don't know if we have conventions.

I think our only convention is to be inconsistent. 😁

**Pull request merged**
